services:
  db_pg:
    image: postgres:15-alpine
    env_file:
      - .env
    ports:
      - "5430:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - my_networks 

networks:
  my_networks:

volumes:
  db_data: