# Generated by Django 5.0.7 on 2024-08-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_bookinstance_borrower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='photo',
            field=models.ImageField(blank=True, help_text='Загрузите изображение обложки', upload_to='images', verbose_name='Изображение обложки'),
        ),
    ]
