# Generated by Django 5.0.7 on 2024-08-16 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_book_raring'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='raring',
            new_name='rating',
        ),
    ]
